name: CI/CD Pipeline - release/* branches

on:
  push:
    branches: [ "release/*" ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      node-version: 24.x

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      node-version: 24.x

  publish:
    permissions:
      contents: write
      id-token: write
    needs: test
    uses: ./.github/workflows/publish.yml
    with:
      node-version: 24.x
    secrets: inherit
